# Generated by Django 3.1.3 on 2021-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
